---
- name: Install AIDE
  ansible.builtin.apt:
    name:
      - aide
      - aide-common
    state: present

- name: Enable daily AIDE cron
  ansible.builtin.lineinfile:
    path: /etc/default/aide
    regexp: '^CRON_DAILY_RUN='
    line: 'CRON_DAILY_RUN=yes'
    create: true

- name: Initialize AIDE database when missing
  ansible.builtin.command: aideinit
  args:
    creates: /var/lib/aide/aide.db.new
  async: 3600
  poll: 20
  check_mode: false

- name: Promote AIDE database into place
  ansible.builtin.copy:
    src: /var/lib/aide/aide.db.new
    dest: /var/lib/aide/aide.db
    remote_src: true
    force: false
    mode: "0600"
    owner: root
    group: root
